import Head from "next/head";
import { useRouter } from "next/router";
import { unstable_getServerSession } from "next-auth";
import { authOptions } from "/pages/api/auth/[...nextauth]";
import Header from "components/Header";
import Menu from "components/Menu";
import Section from "components/Section";
import useSections from "hooks/useSections";

export default function List({ list }) {
    const { sections, loading } = useSections(list.id);
    console.log(sections);
    return (
        <>
            <Head>
                <title>Verdel</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/logo.svg" />
            </Head>
            <div className="min-h-screen inline-flex w-full justify-center bg-gray-200">
                <Menu />
                <main className="w-full">
                    <Header listTitle={list.name}/>
                    {  
                        loading 
                            ? <div>loading..</div>
                            : sections?.map(section => <Section key={section.id} section={section}/>)
                    }
                </main>
            </div>
        </>
    )
}

export async function getServerSideProps(context) {
    const session = await unstable_getServerSession(context.req, context.res, authOptions)
    if (!session) {
        return {
            redirect: {
                destination: "/login",
            },
        };
    }
    const { listId } = context.query
    const res = await fetch(`http://localhost:3000/api/lists/${listId}`, {
        headers: {
            Cookie: context.req.headers.cookie
        }
    })
    const list = await res.json()
    console.log({ list, listId })
    return {
        props: {
            list
        }
    }
}
