import Head from "next/head";
import Menu from "../components/Menu";
// import styled from "styled-components"
import { unstable_getServerSession } from "next-auth/next";
import { authOptions } from "./api/auth/[...nextauth]";
import { ArrowDownIcon, PencilSquareIcon } from '@heroicons/react/24/outline'


export default function Home() {
  return (
    <>
      <div className="min-h-screen inline-flex w-full justify-center bg-gray-200">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/logo.svg" />
        </Head>
        <Menu />
        <main className="w-full ">
          <div className="bg-orange-600 w-3/4 h-10 mt-2 rounded-lg">
            <button className="w-6 h-6 bg-orange-600 ml-80 mt-2 rounded-lg">
              <PencilSquareIcon className="h-6 w-6 transition hover:stroke-gray-200" />
            </button>
            <button className="w-6 h-6 bg-orange-600 ml-5 mt-2">
              <ArrowDownIcon className="h-6 w-6 transition hover:stroke-gray-200"/>
            </button>
          </div>
          <div className="bg-gray-700 w-3/4 h-80 rounded-lg">

          </div>
        </main>
      </div>
    </>
  );
}

export const getServerSideProps = async (context) => {
  const session = await unstable_getServerSession(
    context.req,
    context.res,
    authOptions
  );

  if (!session) {
    return {
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  return {
    props: { session },
  };
};
